### ISSUE TITLE
Cannot find namespace in 'JSX'

### ISSUE THREAD

**Issue by arsenx** [ionic-team/stencil-state-tunnel#12]
When using stencil @one I get the following error.

<img width="1037" alt="Screen Shot 2019-05-16 at 1 05 45 PM" src="https://user-images.githubusercontent.com/5718879/57883710-0967c800-77f5-11e9-859f-f79e31c9787f.png">

Probably has to be compiled and published to npm using the new stencil one

**Comment by yanting-larsen** [comment]
I also have the same when trying to stencil router 
<img width="1234" alt="Screen Shot 2019-05-30 at 19 32 33" src="https://user-images.githubusercontent.com/17611844/58651537-dacc1000-8311-11e9-9c73-0ed486ee2244.png">

**Comment by daniellacerdaweb** [comment]
Updates the @stencil/router
