### ISSUE TITLE
Documentation does not mention how is this project different from ionic-team/stencil-redux

### ISSUE THREAD

**Issue by atulvani** [ionic-team/stencil-state-tunnel#2]
The documentation should mention how is this project different from https://github.com/ionic-team/stencil-redux

Optionally, "when to use which one" as well.

**Comment by jthoms1** [comment]
If you are building an app use stencil-redux.  If you are building a component library then most likely you will use state-tunnel.

**Comment by jthoms1** [comment]
I have updated the wiki documentation to explicitly state that this should be used for component libraries and not applications. https://github.com/ionic-team/stencil-state-tunnel/wiki

**Comment by atulvani** [comment]
So if I create a component using stencil-state-tunnel, let's say accordion, I can then use multiple of those on the same page of an application and their states won't interfere with eachother?
