### ISSUE TITLE
Access consumer outside of render()

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil-state-tunnel#7]
Is there any way to access the consumer outside of the render() hook? Something similar to React's `this.context`, for example:

```
componentDidLoad() {
  this.context.increment()
}
```

Note: The docs state "There are other approaches to consuming the information" - which approaches exactly?

**Comment by jthoms1** [comment]
There is a function called injectProps that allows you to do this.  I will leave this issue open for documenting it.

https://github.com/ionic-team/stencil-state-tunnel/blob/405dc3e7a6bfb71420508a7e947a3f94c77cdc55/packages/demo/src/components/demo-create-message.tsx#L86

**Comment by jthoms1** [comment]
I have added a page to the wiki for this. https://github.com/ionic-team/stencil-state-tunnel/wiki/Injecting-Props-into-a-component
